window.ADYA_SCHEDULE = [
  {
    id: "morning-offline-rv-dental",
    title: "Morning Group Class",
    time: "7:00 AM - 8:00 AM",
    startHour: 7,
    duration: "60 mins",
    period: "morning",
    mode: "offline",
    format: "Group class",
    location: "RV Dental College, JP Nagar 1st Phase, Bengaluru",
    description: "Traditional Yoga group practice with in-person guidance.",
  },
  {
    id: "morning-online-women",
    title: "Women's Only Group Class",
    time: "10:00 AM - 11:00 AM",
    startHour: 10,
    duration: "60 mins",
    period: "morning",
    mode: "online",
    format: "Women's only group class",
    location: "Online",
    description: "A women-only online batch for steady practice from home.",
  },
  {
    id: "evening-online-five",
    title: "Evening Group Class",
    time: "5:00 PM - 6:00 PM",
    startHour: 17,
    duration: "60 mins",
    period: "evening",
    mode: "online",
    format: "Group class",
    location: "Online",
    description: "An evening online batch for breath-led movement and consistency.",
  },
  {
    id: "evening-online-six",
    title: "Evening Group Class",
    time: "6:00 PM - 7:00 PM",
    startHour: 18,
    duration: "60 mins",
    period: "evening",
    mode: "online",
    format: "Group class",
    location: "Online",
    description: "A later evening online batch for students after work or college.",
  },
];
